# Usa una imagen base de Python
FROM python:3.8-slim

# Configura el directorio de trabajo
WORKDIR /app

# Copia el archivo de aplicación al contenedor
COPY app.py /app

# Comando por defecto al iniciar el contenedor
CMD ["python", "app.py"]
